services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    networks:
      - caddy_net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./knocker.yaml:/app/knocker.yaml
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - knocker

  knocker:
    image: ghcr.io/fariszr/knocker:main
    restart: unless-stopped
    networks:
      - caddy_net
    volumes:
      - ./knocker.yaml:/knocker.yaml
      - ./knocker_data:/data
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    # REQUIRED OPTIONS for firewalld integration
    # user: "0:0"  # Run as root
    # userns_mode: host
    # cap_add:
    #   - NET_ADMIN

networks:
  caddy_net:
    # Enable IPv6 for this network
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        # Define subnets for both IPv4 and IPv6.
        # Your 'trusted_proxies' in knocker.yaml should include these.
        - subnet: 172.16.238.0/24
        - subnet: fd00:dead:beef::/64

volumes:
  caddy_data:
  caddy_config:
