services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    networks:
      - caddy_net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../knocker-firewalld.yaml:/app/knocker.yaml:ro
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--watch"]
    depends_on:
      - knocker-firewalld

  knocker-firewalld:
    build:
      context: ..
      dockerfile: dev/Dockerfile.firewalld
    restart: unless-stopped
    privileged: true  # Required for firewalld to manage iptables
    networks:
      - caddy_net
    environment:
      - KNOCKER_CONFIG_PATH=/app/knocker.yaml
    volumes:
      - ../knocker-firewalld.yaml:/app/knocker.yaml:ro
      - knocker_data:/data
      # Mount D-Bus socket for container communication (if host has firewalld)
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    # For host firewalld integration (alternative approach):
    # network_mode: "host"  # Required to manage host firewall rules
    # volumes:
    #   - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

networks:
  caddy_net:
    # Enable IPv6 for this network
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        # Define subnets for both IPv4 and IPv6.
        # Your 'trusted_proxies' in knocker.yaml should include these.
        - subnet: 172.29.238.0/24
        - subnet: fd00:dead:c0de::/64

volumes:
  caddy_data:
  caddy_config:
  knocker_data: