name: Run Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - pyproject.toml
      - uv.lock
      - Dockerfile
      - .github/workflows/**
      - src/**
      - dev/**
      - tests/**
  push:
    branches: [ "main" ]
    paths:
      - pyproject.toml
      - uv.lock
      - Dockerfile
      - .github/workflows/**
      - src/**
      - dev/**
      - tests/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: 'pyproject.toml'

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true

    - name: Sync project dependencies
      run: uv sync --locked --all-groups

    - name: Run Ruff lint checks
      run: uv run --group lint ruff check .

    - name: Run Ruff format checks
      run: uv run --group lint ruff format --check .

    - name: Run ty checks
      run: uv run --group type ty check

    - name: Run unit tests
      run: uv run pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Run docker compose stack
      run: docker compose -f dev/docker-compose.ci.yml up -d --build

    - name: Wait for services to be healthy
      run: sleep 10 # Simple wait for services to start

    - name: Make integration test script executable
      run: chmod +x dev/local_integration_tests.sh

    - name: Run integration tests
      run: ./dev/local_integration_tests.sh
