name: Run Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install -r src/requirements.txt

    - name: Run unit tests
      run: PYTHONPATH=src python3 -m pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run docker compose stack
      run: docker compose -f dev/docker-compose.ci.yml up -d --build

    - name: Wait for services to be healthy
      run: sleep 10 # Simple wait for services to start

    - name: Make integration test script executable
      run: chmod +x dev/local_integration_tests.sh

    - name: Run integration tests
      run: ./dev/local_integration_tests.sh